# Generated by Django 2.2 on 2021-08-02 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_auto_20210803_0014'),
    ]

    operations = [
        migrations.RenameField(
            model_name='items',
            old_name='product',
            new_name='prodt',
        ),
    ]
